### ISSUE TITLE
Share Button

### ISSUE THREAD

**Issue by johnRedden** [johnRedden/OpenGraph#36]
Should give an URL to by copied and pasted in a discussion board...

...openGraphingCalculator.com?3x^2+2x+5

Some way of reproducing the graph in the url??  API??

**Comment by pgonzbecer** [comment]
I have a thing already implemented, but it is shotty as hell

**Comment by pgonzbecer** [comment]
It's a little bit nicer now, made it so it reads it in latex, because any other way is all screwy So:

...openGraphingCalculator.com?3x^2+2x+5 will come out smooth, and anything complex could come up as latex or something. All we need is a share button that gets all the entries, and squishes them onto the api in latex form. So the user doesn't really have to mess with latex

Edit:
Let me filter out the junk for what needs to be done next:
-  Get Share button to work

**Comment by pgonzbecer** [comment]
I believe this is done
