### ISSUE TITLE
one Calculus Gremlin left

### ISSUE THREAD

**Issue by johnRedden** [johnRedden/OpenGraph#62]
when making a definite integral... the value changes slightly when dragging over the graph.  There is some onMove somewhere slightly affecting the value??  Can't imagine where it is.

**Comment by pgonzbecer** [comment]
Agh! Shnizzles. Problem was simple, it was updating the board on mouse movement. It was internal trouble with the `update()` function. But that causes some trouble, since I basically commented out the function in order for the graph to integrate better, that leaves the mobile scene straight under the bus. So we got this done, but we NEED TO GET MOBILE READY. I think we postponed this for too long. I will post up some issues, so if I don't catch them by tonight we can fix them by tomorrow
